### ISSUE TITLE
Recursive power algorithm in C++

### ISSUE THREAD

**Issue by vineetsharma36** [mohit103/sample-programs#27]
Please assign me this program

**Comment by mohit103** [comment]
Please write a quality program and send a pull request!

**Comment by abhi26ak** [comment]
Could you Please Assign this issue to me. I also want to contribute.

**Comment by mohit103** [comment]
@abhi26ak done!

**Comment by mohit103** [comment]
@abhi26ak You may check the code submitted by @vineetsharma36. Also, you are free to contribute other programs,
